### PR TITLE
Karina

### PR DESCRIPTION
**Pull request by KarinaFrei**
Completed, please advise.

### CODE REVIEW

**Review by AnnaLoshak — APPROVED** [review]
Good work

**Review by Aramat16ukr — APPROVED** [review]
Good job!

**Review by BadamkhandB — APPROVED** [review]

**Review by ZaierAouani — APPROVED** [review]
Good work!

**Review by VeronikaKrasnokutska — APPROVED** [review]
Perfect!

**Review by natebell510 — APPROVED** [review]
a

**Review by tsjuder1 — APPROVED** [review]
All good!

**Pull request merged**
